version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zoo
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
#    ports:
#      - "2181:2181"
    networks:
      - kafkanet

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
#    ports:
#      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafkanet

  postgres:
    image: postgres:13
    container_name: postgres
#    ports:
#      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=credit_db
    networks:
      - kafkanet

  conveyor:
    image: conveyor
    container_name: conveyor
#    ports:
#      - "8080:8080"
    networks:
      - kafkanet

  deal:
    image: deal
    container_name: deal
#    ports:
#      - "8081:8081"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - zookeeper
      - kafka
      - postgres
      - conveyor
    networks:
      - kafkanet

  application:
    image: application
    container_name: application
#    ports:
#      - "8082:8082"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - zookeeper
      - kafka
      - postgres
      - conveyor
      - deal
    networks:
      - kafkanet

  dossier:
    image: dossier
    container_name: dossier
#    ports:
#      - "8083:8083"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - zookeeper
      - kafka
      - postgres
      - conveyor
      - deal
      - application
    networks:
      - kafkanet

  gateway:
    image: gateway
    container_name: gateway
    ports:
      - "8090:8090"
    environment:
          - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - zookeeper
      - kafka
      - postgres
      - conveyor
      - deal
      - application
      - dossier
    networks:
      - kafkanet

volumes:
  pgdata:

networks:
  kafkanet:
